### ISSUE TITLE
Пример Aruco. Повторное выполнение команд в дочерних процессах.

### ISSUE THREAD

**Issue by Filarius** [geoscan/pioneer_sdk#1]
В данном примере (как минимум под виндой) весь исполняемый код вне обертки __main__ будет также выполняться и в дочерних процессах
https://github.com/geoscan/pioneer_sdk/blob/01ba38d34e327936cc8991c4e2cde0b362a3c927/examples/aruco_flight.py#L101

Из-за этого квадракоптер получает команды в такой последовательности
arm
takeoff
arm
arm

Как следствие - взлетает, получает ошибку, вырубает лопасти, падает.

**Comment by thinkabout4x** [comment]
Спасибо большое за найденную ошибку! Поправил.
